# produce PDF output by default
$pdf_mode = 1;

#add synctex extensions so they are cleaned
push @generated_exts, 'synctex', 'synctex.gz';

# clean up more temporary files
$clean_ext .=  ' run.xml out.ps bbl synctex.gz';

# directory for junk files
$aux_dir='latex_junk';
$out_dir='output';

#add synctex extensions so they are cleaned
push @generated_exts, 'synctex', 'synctex.gz';

# clean files generated by custom dependencies
$cleanup_includes_cusdep_generated = 1;
# clean files generated by latex
$cleanup_includes_generated = 1;

# use Edge as viewer
# $pdf_previewer = "start microsoft-edge:";

# configure pdflatex: parse output, don't stop on errors
$pdflatex = 'texfot pdflatex -interaction=nonstopmode -shell-escape';

# reduce unnecessary output
$silent = 1;